# Generated by Django 3.0.3 on 2020-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_owed',
            field=models.CharField(default='1000gh', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default='77 Home A', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Orange Lake', max_length=150),
        ),
    ]
