# Generated by Django 3.0.3 on 2020-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200515_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_owedtolls',
            field=models.CharField(default='1000gh', max_length=150),
        ),
    ]
