# Generated by Django 3.0.3 on 2020-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Due_date',
            field=models.CharField(default='Orange Lake', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='Multiplier',
            field=models.CharField(default='Orange Lake', max_length=150),
        ),
    ]
