# Generated by Django 3.0.3 on 2020-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200518_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Month',
            field=models.CharField(default='Orange Lake', max_length=150),
        ),
    ]
