# Generated by Django 3.0.3 on 2020-05-23 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default='1000', max_digits=7),
        ),
        migrations.CreateModel(
            name='Bankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountinaccount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('specialnumber', models.CharField(default='0000', max_length=150)),
                ('lastthreedig', models.CharField(default='0000', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
