# Generated by Django 3.0.3 on 2020-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_creditcardpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpayments',
            name='Mail',
            field=models.CharField(default='Enter an email to receive receipt', max_length=150),
        ),
        migrations.AddField(
            model_name='creditcardpayments',
            name='Paymet_Comment',
            field=models.CharField(default='0000', max_length=150),
        ),
        migrations.AddField(
            model_name='creditcardpayments',
            name='signed_by',
            field=models.CharField(default='0000', max_length=150),
        ),
    ]
