# Generated by Django 3.0.3 on 2020-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Account_Name',
            field=models.CharField(default='1000gh', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='Bank_UC',
            field=models.CharField(default='1000gh', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='CUL',
            field=models.CharField(default='0000', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='Card_Number',
            field=models.CharField(default='0000', max_length=150),
        ),
    ]
