# Generated by Django 3.0.3 on 2020-06-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Town', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('House_Number', models.CharField(max_length=100)),
                ('Owner', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
